#thymeleaf配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      enabled: false
      location: F:\temp\tomcat\upload
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8

  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/skyline-admin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /admin
    encoding:
      enabled: true
      force: true
      charset: UTF-8


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1 # deleted 1
      logic-not-delete-value: 0 # default 0


#debug: true


gaia:
  id:
    type: vesta

admin:
    oss:
      storeType: LOCAL
      local: E:/nginx-1.23.2/data/statics
      endpoint: http://localhost:9898